name = "storefront"
type = "javascript"

account_id = "your-account-id"
workers_dev = true
compatibility_date = "2024-12-10"

[build]
  command = "npm run build"
  directory = "dist"

[[pages]]
  build_output_dir = "dist"
  public_dir = "public"
